version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./database:/var/www/html/database
      # Monter la configuration vhost personnalisée pour pointer vers /public
      - ./docker/apache-vhost.conf:/etc/apache2/sites-available/000-default.conf